name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: install Electron 
        run: npm install electron

      - name: install Forge 
        run: npm install @electron-forge/cli
        
      - name: import Forge 
        run: npx electron-forge import
        
      - name: build app 
        run: npm make

